# Generated by Django 6.0.3 on 2026-03-05 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('ubicacion_maps', models.URLField(blank=True, null=True)),
                ('router', models.CharField(max_length=100)),
                ('tipo_ip', models.CharField(choices=[('Estatica', 'Estatica'), ('Dinamica', 'Dinamica')], max_length=10)),
                ('ip', models.GenericIPAddressField()),
                ('fecha_inicio', models.DateField()),
                ('dia_pago', models.IntegerField()),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('año', models.IntegerField()),
                ('fecha_generacion', models.DateField(auto_now_add=True)),
                ('pagado', models.BooleanField(default=False)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='facturas/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes_app.cliente')),
            ],
        ),
    ]
