# Generated by Django 6.0.3 on 2026-03-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado_pago',
            field=models.BooleanField(default=False),
        ),
    ]
