# Generated by Django 6.0.3 on 2026-03-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0003_antena_cliente_antena'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
